### PR TITLE
WIP: refactoring to libraries with better app isolation, better testing

### PR DESCRIPTION
**Pull request by deanwampler**
These changes are massive, too large to review easily. Sorry I couldn't do it in smaller steps. To review, it would probably be easiest to start with one of the app directories, e.g., `wine-quality-ml` or `airline-flights-ml`, look at the implementations (which are smaller than they used to be...), and then work out to the library code they use in `pipelinesx` and `model-serving`.

I'm leaving on vacation Wednesday, so I wanted to give you guys a chance to review. It's still "work in progress" because I need to debug some issues with the Wine app. (The TensorFlow code is very complicated.) I've tested the other two apps and they work fine, although the Recommender can't actually score anything without a service to call. Hopefully I can remove the "WiP" tomorrow (Monday).

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by deanwampler** [comment]
Forgot to mention that I created a GitHub project to adds tasks for further work. https://github.com/lightbend/pipelines-model-serving/projects/1

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by deanwampler** [comment]
I've completed the conversion with the Avro hacks that Boris and I discussed. The Airline Flights app works fine. The recommender app runs, but of course has no server to call for scoring. 

The Wine app needs to have a PVC defined; I get the following error attempting to deploy:

```shell
$ kubectl pipelines deploy docker-registry-default.gsa2.lightbend.com/lightbend/wine-quality-ml-deanwampler:181-67a70ce-dirty
Using docker API version: 1.40
181-67a70ce-dirty: Pulling from lightbend/wine-quality-ml-deanwampler
Digest: sha256:96e28ea388666576377e628a1f850d8f8558daea8079e82478fd5c07c1116669
Status: Image is up to date for docker-registry-default.gsa2.lightbend.com/lightbend/wine-quality-ml-deanwampler:181-67a70ce-dirty
docker-registry-default.gsa2.lightbend.com/lightbend/wine-quality-ml-deanwampler:181-67a70ce-dirty
Volume mount `persistence-data-mount` needs to be configured with an existing persistent volume claim
```

I haven't tried running all the "main" routines. All the unit tests pass. All of the apps should be run longer than the few minutes I ran them.

One other thing, looking at the egress of recommender, the error fields are empty; they should have a message about "no model".

That's it for me. I'm off for a vacation the next ~10 days. I'll reply to email occasionally

**Comment by deanwampler** [comment]
One more thing ;) I suggest tagging the `master` branch with some marker, just in case when the merge finally happens but something fails badly, you have a place to return to...

**Pull request merged**
